import emailValidation from './email/email-validation'
import dateTimeValidation from './dateTime/datetime-validation'
import phoneValidation from './phone/phone-validation'
import pathValidation from './path/path-validation'
import creditCardValidation from './path/creditcard-validation'
